---
title: "Conkling_Prepare_data_for_dashboard"
output: html_notebook
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(sf)
library(tidyverse)
library(readxl)
library(scales)
library(grid)
```


##Load Data for all 3 plots
```{r}
#Load College Scorecard
college_scorecard_19_20 <- read.csv("https://raw.githubusercontent.com/tconkling47/543_deliverable_2/main/college_scorecard_19-20.csv")

#Load Student Debt Data
url <- "https://raw.githubusercontent.com/tconkling47/543_deliverable_2/main/recent_cohort_field_of_study.xlsx"
destfile <- "recent_cohort_field_of_study.xlsx"
curl::curl_download(url, destfile)
recent_cohort_field_of_study <- read_excel(destfile)
```


##Plot 2: Bivariate-Categorical Plot
```{r}
collegetypes <- college_scorecard_19_20 %>%
  mutate(
    type = case_when(CONTROL==1    ~ 'Public'
                     ,CONTROL==2 & RELAFFIL=='NULL' ~ 'Non-Profit'
                     , CONTROL==2 & RELAFFIL!='NULL'      ~ 'Religious'
                     , CONTROL==3     ~ 'For-Profit')
  ) %>%
  select(UNITID, INSTNM, type)
debt_pre_merge <- recent_cohort_field_of_study %>%
  filter(CREDLEV==3) %>%
  select(UNITID, INSTNM, CIPCODE, CIPDESC, CREDLEV, CREDDESC, DEBT_ALL_STGP_ANY_N, DEBT_ALL_STGP_ANY_MEAN)
data1 <- debt_pre_merge %>%
  filter(DEBT_ALL_STGP_ANY_N != 'PrivacySuppressed' 
         & DEBT_ALL_STGP_ANY_MEAN != 'PrivacySuppressed')
data2 <- transform(data1, DEBT_ALL_STGP_ANY_N = as.numeric(DEBT_ALL_STGP_ANY_N),
                    DEBT_ALL_STGP_ANY_MEAN = as.numeric(DEBT_ALL_STGP_ANY_MEAN))
data3 <- data2 %>%
  mutate(total_debt = DEBT_ALL_STGP_ANY_N*DEBT_ALL_STGP_ANY_MEAN)
data4 <- data3 %>%
  group_by(UNITID) %>%
  summarise(total_students_in_school_sample = sum(DEBT_ALL_STGP_ANY_N),
            total_debt_in_school_sample = sum(total_debt)) %>%
  mutate(school_average_student_debt = total_debt_in_school_sample/total_students_in_school_sample)
data5 <- merge(data4, collegetypes, by="UNITID")
base=ggplot(data=data5,
            aes(x=type,y=school_average_student_debt))

base + geom_boxplot() + coord_flip()
base2=ggplot(data=data5,
            aes(x=reorder(type,
                          school_average_student_debt,
                          median),
                y=school_average_student_debt)) 
boxplot_2 = base2 + geom_boxplot()
# flipping
boxplot_3 = boxplot_2  + coord_flip()
boxplot_3
### Adding title and source
titleText="Public Colleges & Universities Leave Bachelor's Degree Graduates with"
subtitleText="Less Student Debt Than Other Types of Institutions"
sourceText='Source: US Department of Education'
boxplot_4 = boxplot_3 + labs(title=titleText,
                             subtitle = subtitleText,
                   x='Institution Type',
                   y= "Average Student Debt of Bachelor's Degree Graduate",
                   caption = sourceText) + theme_classic()
boxplot_4
boxplot_5 = boxplot_4 + theme(plot.caption = element_text(hjust = 0))
boxplot_5
boxplot_6 = boxplot_5 + scale_y_continuous(labels=scales::dollar_format())
boxplot_6
boxplot7 = boxplot_6 + theme(
    plot.title = element_text(face = 'bold', size = 15, hjust=0.3, vjust = 0),
    plot.subtitle = element_text(face = 'bold', size = 15, hjust=0.4, vjust=0),
    axis.title = element_text(face = 'bold'),
    axis.title.y = element_text(vjust = 2.5),
    axis.title.x = element_text(vjust = 0)
  ) 
boxplot7
grob <- grobTree(textGrob("e.g. Ivy League, Small Liberal Arts Colleges", x=0.6,  y=0.34, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot8 = boxplot7 + annotation_custom(grob)
boxplot8
grob2 <- grobTree(textGrob("e.g. University of Washington, Ohio State ", x=0.55,  y=0.1, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot9 = boxplot8 + annotation_custom(grob2)
boxplot9
grob3 <- grobTree(textGrob("e.g. Notre Dame, BYU", x=0.72,  y=0.58, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot10 = boxplot9 + annotation_custom(grob3)
boxplot10
grob4 <- grobTree(textGrob("e.g. Univ. of Phoenix", x=0.8,  y=0.82, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot11 = boxplot10 + annotation_custom(grob4)
boxplot11
#saving
saveRDS(boxplot11,file = 'boxplot.rds')
```

