---
title: "Conkling_Prepare_data_for_dashboard"
output: html_notebook
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(sf)
library(tidyverse)
library(readxl)
library(scales)
library(grid)
```


##Load Data for all 3 plots
```{r}
#Load College Scorecard
college_scorecard_19_20 <- read.csv("https://raw.githubusercontent.com/tconkling47/543_deliverable_2/main/college_scorecard_19-20.csv")

#Load Student Debt Data
url <- "https://raw.githubusercontent.com/tconkling47/543_deliverable_2/main/recent_cohort_field_of_study.xlsx"
destfile <- "recent_cohort_field_of_study.xlsx"
curl::curl_download(url, destfile)
recent_cohort_field_of_study <- read_excel(destfile)

url <- "https://raw.githubusercontent.com/tconkling47/543_Deliverable_3_Map/main/Flagship_State_Universities.xlsx"
destfile <- "Flagship_State_Universities.xlsx"
curl::curl_download(url, destfile)
flagships <- read_excel(destfile)
```

##Plot 1: Univariate Plot
```{r}
collegetypes <- college_scorecard_19_20 %>%
  mutate(
    type = case_when(CONTROL==1    ~ 'Public'
                     ,CONTROL==2 & RELAFFIL=='NULL' ~ 'Non-Profit'
                     , CONTROL==2 & RELAFFIL!='NULL'      ~ 'Religious'
                     , CONTROL==3     ~ 'For-Profit')
  ) %>%
  select(INSTNM, STABBR, type, TUITIONFEE_IN, TUITIONFEE_OUT)
collegetypes2 <- transform(collegetypes, TUITIONFEE_IN = as.numeric(TUITIONFEE_IN),
                    TUITIONFEE_OUT = as.numeric(TUITIONFEE_OUT))
college_tuition <- collegetypes2 %>%
  group_by(type) %>%
  summarise(mean(TUITIONFEE_OUT, na.rm=TRUE))
college_tuition[3, 1] <- "Public, Out-of-State"
college_tuition2 <- collegetypes2 %>%
  group_by(type) %>%
  summarise(mean(TUITIONFEE_IN, na.rm=TRUE)) %>%
  filter(type=="Public")
college_tuition2[1,1] <- "Public, In-State"
college_tuition[nrow(college_tuition) + 1,] <- college_tuition2
college_tuition <- college_tuition %>%
  rename(tuition = `mean(TUITIONFEE_OUT, na.rm = TRUE)`)
base= ggplot(data = college_tuition, 
             aes(x = reorder(type, tuition),
                 y = tuition)) + geom_bar(fill = "#B1CED0", stat = 'identity')
#add a theme
plot1 = base + theme_classic()
titleText='Public Institutions Have The Lowest Tuition Rates among U.S. Colleges'
sourceText='Source: US Department of Education'

plot2 = plot1 + labs(title=titleText,
                     x =NULL, 
                     y = 'Average Yearly Tuition',
                     caption = sourceText) 
#customize y axis
plot3 = plot2 + scale_y_continuous(breaks=c(0,5000,10000,15000,20000,25000, 30000),
                                   limits = c(0,30000), labels=scales::dollar_format()
                                    )


#reposition text
plot4 = plot3 + theme(plot.caption = element_text(hjust = 0),
                      plot.title = element_text(hjust=0.5))
#create labels for the bars
LABELS=paste0('$', round(college_tuition$tuition,0))

plot5 = plot4 + geom_text(hjust=0.5, vjust = 1.2,
                          size = 5,
                          aes(y = tuition,
                              label = LABELS))
#Add a couple final aesthetic touches
plot6 = plot5 + theme(
    plot.title = element_text(face = 'bold', size = 14)
  )
#export image
ggsave('Conkling_Univariate_PUBPOL543.jpg', device = 'jpeg', width = 7.75, height = 5, dpi = 300)
#saving
saveRDS(plot6,file = 'univariate.rds')
```



##Plot 2: Bivariate-Categorical Plot
```{r}
collegetypes <- college_scorecard_19_20 %>%
  mutate(
    type = case_when(CONTROL==1    ~ 'Public'
                     ,CONTROL==2 & RELAFFIL=='NULL' ~ 'Non-Profit'
                     , CONTROL==2 & RELAFFIL!='NULL'      ~ 'Religious'
                     , CONTROL==3     ~ 'For-Profit')
  ) %>%
  select(UNITID, INSTNM, type)
debt_pre_merge <- recent_cohort_field_of_study %>%
  filter(CREDLEV==3) %>%
  select(UNITID, INSTNM, CIPCODE, CIPDESC, CREDLEV, CREDDESC, DEBT_ALL_STGP_ANY_N, DEBT_ALL_STGP_ANY_MEAN)
data1 <- debt_pre_merge %>%
  filter(DEBT_ALL_STGP_ANY_N != 'PrivacySuppressed' 
         & DEBT_ALL_STGP_ANY_MEAN != 'PrivacySuppressed')
data2 <- transform(data1, DEBT_ALL_STGP_ANY_N = as.numeric(DEBT_ALL_STGP_ANY_N),
                    DEBT_ALL_STGP_ANY_MEAN = as.numeric(DEBT_ALL_STGP_ANY_MEAN))
data3 <- data2 %>%
  mutate(total_debt = DEBT_ALL_STGP_ANY_N*DEBT_ALL_STGP_ANY_MEAN)
data4 <- data3 %>%
  group_by(UNITID) %>%
  summarise(total_students_in_school_sample = sum(DEBT_ALL_STGP_ANY_N),
            total_debt_in_school_sample = sum(total_debt)) %>%
  mutate(school_average_student_debt = total_debt_in_school_sample/total_students_in_school_sample)
data5 <- merge(data4, collegetypes, by="UNITID")
base=ggplot(data=data5,
            aes(x=type,y=school_average_student_debt))

base + geom_boxplot() + coord_flip()
base2=ggplot(data=data5,
            aes(x=reorder(type,
                          school_average_student_debt,
                          median),
                y=school_average_student_debt)) 
boxplot_2 = base2 + geom_boxplot()
# flipping
boxplot_3 = boxplot_2  + coord_flip()
boxplot_3
### Adding title and source
titleText="Public Colleges & Universities Leave Bachelor's Degree Graduates"
subtitleText="With Less Student Debt Than Other Types of Institutions"
sourceText='Source: US Department of Education'
boxplot_4 = boxplot_3 + labs(title=titleText,
                             subtitle = subtitleText,
                   x='Institution Type',
                   y= "Average Student Debt of Bachelor's Degree Graduate",
                   caption = sourceText) + theme_classic()
boxplot_4
boxplot_5 = boxplot_4 + theme(plot.caption = element_text(hjust = 0))
boxplot_5
boxplot_6 = boxplot_5 + scale_y_continuous(labels=scales::dollar_format())
boxplot_6
boxplot7 = boxplot_6 + theme(
    plot.title = element_text(face = 'bold', size = 14.65, hjust=0, vjust = 0),
    plot.subtitle = element_text(face = 'bold', size = 14.65, hjust=0, vjust=0),
    axis.title = element_text(face = 'bold'),
    axis.title.y = element_text(vjust = 2.5),
    axis.title.x = element_text(vjust = 0)
  ) 
boxplot7
grob <- grobTree(textGrob("e.g. Ivy League, Liberal Arts Colleges", x=0.6,  y=0.34, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot8 = boxplot7 + annotation_custom(grob)
boxplot8
grob2 <- grobTree(textGrob("e.g. University of Washington, Ohio State ", x=0.55,  y=0.1, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot9 = boxplot8 + annotation_custom(grob2)
boxplot9
grob3 <- grobTree(textGrob("e.g. Notre Dame, BYU", x=0.76,  y=0.58, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot10 = boxplot9 + annotation_custom(grob3)
boxplot10
grob4 <- grobTree(textGrob("e.g. DeVry Univ.", x=0.83,  y=0.82, hjust=0,
  gp=gpar(col="black", fontsize=11, fontface="italic")))
boxplot11 = boxplot10 + annotation_custom(grob4)
boxplot11
#export image
boxplot11
ggsave('Conkling_Bivariate_Cat-Numerical_Graph_PUBPOL543.jpg', device = 'jpeg', width = 7.75, height = 5, dpi = 300)
#saving
saveRDS(boxplot11,file = 'boxplot.rds')
```


##Plot 3: Map Plot
```{r}
flagships2 <- flagships%>%
  select(UNITID, INSTNM, UGDS, TUITIONFEE_IN, LONGITUDE, LATITUDE)
debt_pre_merge <- recent_cohort_field_of_study %>%
  filter(CREDLEV==3) %>%
  select(UNITID, INSTNM, CIPCODE, CIPDESC, CREDLEV, CREDDESC, DEBT_ALL_STGP_ANY_N, DEBT_ALL_STGP_ANY_MEAN)
data1 <- debt_pre_merge %>%
  filter(DEBT_ALL_STGP_ANY_N != 'PrivacySuppressed' 
         & DEBT_ALL_STGP_ANY_MEAN != 'PrivacySuppressed')
data2 <- transform(data1, DEBT_ALL_STGP_ANY_N = as.numeric(DEBT_ALL_STGP_ANY_N),
                    DEBT_ALL_STGP_ANY_MEAN = as.numeric(DEBT_ALL_STGP_ANY_MEAN))
data3 <- data2 %>%
  mutate(total_debt = DEBT_ALL_STGP_ANY_N*DEBT_ALL_STGP_ANY_MEAN)
data4 <- data3 %>%
  group_by(UNITID) %>%
  summarise(total_students_in_school_sample = sum(DEBT_ALL_STGP_ANY_N),
            total_debt_in_school_sample = sum(total_debt)) %>%
  mutate(school_average_student_debt = total_debt_in_school_sample/total_students_in_school_sample)
flagships3 <- merge(data4, flagships2, by="UNITID")
flagships4 <- flagships3 %>%
  select(school_average_student_debt, INSTNM, UGDS, TUITIONFEE_IN, LONGITUDE, LATITUDE) %>%
  mutate(debt_category = case_when(
    school_average_student_debt < 17000 ~ "$14,000 - $17,000",
    school_average_student_debt < 20000 ~ "$17,000 - $20,000",
    school_average_student_debt < 23000 ~ "$20,000 - $23,000",
    school_average_student_debt <= 26000 ~ "$23,000 - $26,000",
    school_average_student_debt > 26000 ~ "$26,000 - $29,000"
  ))%>%
  mutate(Enrollment = case_when(
    UGDS < 10000 ~ "<10,000",
    UGDS < 20000 ~ "10,000 - 20,000",
    UGDS < 30000 ~ "20,000 - 30,000",
    UGDS <= 40000 ~ "30,000 - 40,000",
    UGDS > 40000 ~ "40,000 - 75,000"
  )) %>%
  mutate(UGDS2 = UGDS/10000) %>%
     mutate(tuition_category = case_when(
    TUITIONFEE_IN < 9000 ~ "$5,000 - $9,000",
    TUITIONFEE_IN < 13000 ~ "$9,000 - $13,000",
    TUITIONFEE_IN <= 17000 ~ "$13,000 - $17,000",
    TUITIONFEE_IN > 17000 ~ "$17,000 - $20,000"
  ))
linkMap="https://raw.githubusercontent.com/tconkling47/543_Deliverable_3_Map/main/states.geojson" 
mapUSA=read_sf(linkMap)
base=ggplot(data=mapUSA) + geom_sf(fill='grey90',
                                   color=NA) + theme_classic()
base2 = base + coord_sf(xlim = c(-125, -70), ylim = c(25, 49))
base2
flagships_sf = st_as_sf(flagships4,
                        coords = c("LONGITUDE", "LATITUDE"),
                        crs = st_crs(mapUSA)
                        )
base3 = base2 + geom_sf(data=flagships_sf)
base3
map3 = base2 + theme(axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank())
map3
fillTitle="Average Bachelor's Graduate Student Debt"

points = base + geom_sf(data=flagships_sf,
                        shape=21,
                        aes(fill= debt_category,
                            size= Enrollment))

points = points + scale_fill_brewer(palette ='Blues',
                                direction = 1,
                                name=fillTitle) + coord_sf(xlim = c(-125, -70), ylim = c(25, 49))
points = points + theme(axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank())
points
titleText="Flagship Public Universities Enroll Large Student Populations"
subtitleText="Who Have Relatively Low Student Debt Burdens After Graduation"
sourceText='Source: US Department of Education'
points2 = points + labs(title=titleText,
                             subtitle = subtitleText,
                   caption = sourceText)
points2
points3 = points2 + theme(plot.caption = element_text(hjust = 0),
       plot.title = element_text(face = 'bold', size = 13, hjust=0, vjust = 0),
       plot.subtitle = element_text(face = 'bold', size = 13, hjust=0, vjust=0)
)
points3
#export image
ggsave('Conkling_Map_PUBPOL543.jpg', device = 'jpeg', width = 9, height = 4, dpi = 300)
#saving
saveRDS(points3,file = 'map.rds')
```

